name: 'kyverno-action'
description: 'Runs kyverno cli'
branding:
  icon: 'command'
  color: 'red'
inputs:
  command:
    description: 'kyverno command to run'
    required: true
runs:
  using: 'docker'
  image: 'docker://gbaeke/kyverno-action:v1.0.0'
  args:
    - ${{ inputs.command }}
