on: [push]

jobs:
  kyverno-job:
    runs-on: ubuntu-latest
    name: Run kyverno
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run kyverno
        uses: ./ # Uses an action in the root directory
        with:
          command: |
            kyverno version